version: '3.7'

services:
  # マウントして変更を取り込むバージョン(開発用).....と思ったが、同じmain.goを使ってるので反映されない
  # goビルドだけ
  web-mount-volume:
    image: golang
    ports:
      - 8080:8080
    volumes:
      - .:/sample
      - go_volume:/.go
    working_dir: /sample
    command: bash -c "go run main.go"

  # イメージビルドして変更を取り込むバージョン(本番用)
  # イメージビルドとgoビルドで時間がかかる
  web-image-build:
    build: .
    ports:
      - 8081:8080

volumes:
  go_volume:
