version: '3.7'

services:
  web:
    image: golang
    ports:
      - 8080:8080
    volumes:
      - .:/sample
      - go_volume:/.go
    working_dir: /sample
    command: bash -c "go run main.go"

volumes:
  go_volume:
